default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
<<<<<<< HEAD

=======
>>>>>>> heroku/main

development:
  <<: *default
  database: legion_development
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: legion_test
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
<<<<<<< HEAD
  primary: &primary_production
    <<: *default
    database: legion_production
    username: legion
    url: <%= ENV["DATABASE_URL"] %>
    password: <%= ENV["LEGION_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: legion_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: legion_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: legion_production_cable
    migrations_paths: db/cable_migrate
=======
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
>>>>>>> heroku/main
